# Generated by Django 3.1.5 on 2021-02-01 13:15

import Items.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('fullname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=1000)),
                ('landmark', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetable', 'Vegetable')], max_length=20)),
                ('status', models.CharField(choices=[(' ', ' In stock'), ('Out Of Stock', 'out of stock')], max_length=20)),
                ('image', models.ImageField(upload_to=Items.models.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 1, 13, 15, 8, 886537, tzinfo=utc), verbose_name='date published')),
                ('payment_mode', models.CharField(choices=[('Pay On Delivery', 'Pay On Delivery'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Credit Card/Debit Card', 'Credit Card/Debit Card')], default='Pay On Delivery', max_length=100)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=100)),
                ('total_amount', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.customerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.itemdetail')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.orderdetail')),
            ],
        ),
    ]
