# Generated by Django 3.1.5 on 2021-01-29 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='mobile',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 6, 38, 49, 541118, tzinfo=utc), verbose_name='date published'),
        ),
    ]
