# Generated by Django 3.1.5 on 2021-02-01 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 13, 51, 31, 612046, tzinfo=utc), verbose_name='date published'),
        ),
    ]
