# Generated by Django 3.1.5 on 2021-01-29 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_auto_20210129_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 10, 10, 7, 71550, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='payment_mode',
            field=models.CharField(choices=[('Pay On Delivery', 'Pay On Delivery'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Credit Card/Debit Card', 'Credit Card/Debit Card')], default='Pay On Delivery', max_length=100),
        ),
    ]
