# Generated by Django 3.1.5 on 2021-01-29 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_auto_20210129_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 14, 10, 44, 123996, tzinfo=utc), verbose_name='date published'),
        ),
    ]
